DECLARE inventory_count NUMBER;

BEGIN
   SELECT COUNT(*) INTO inventory_count
    FROM USER_TABLES WHERE TABLE_NAME = 'INVENTORY';

   IF inventory_count = 0
       THEN
       EXECUTE IMMEDIATE 'CREATE TABLE INVENTORY(
        PRODUCT_ID NUMBER GENERATED ALWAYS AS IDENTITY (NOCACHE) PRIMARY KEY ,
        PRODUCT_NAME VARCHAR2(100) NOT NULL ,
        PRODUCT_DESCRIPTION VARCHAR2(1000),
        PRODUCT_WHOLESALE NUMBER NOT NULL ,
        PRODUCT_RETAIL NUMBER NOT NULL ,
        PRODUCT_IMAGE VARCHAR2(3000),
        PRODUCT_CATEGORY VARCHAR2(200) NOT NULL,
        PRODUCT_LINK VARCHAR2(2000),
        STATUS VARCHAR2(40) DEFAULT ''ACTIVE'' NOT NULL ,
        CREATED_AT DATE DEFAULT TRUNC(SYSDATE) NOT NULL

                          )';
       ELSE
            DBMS_OUTPUT.PUT_LINE('Table Inventory Already Exists!');
   END IF;
END;

CREATE OR REPLACE PROCEDURE p_add_inventory(

    P_PRODUCT_ID OUT NUMBER,
    P_PRODUCT_NAME IN VARCHAR2,
    P_PRODUCT_DESCRIPTION IN VARCHAR2,
    P_PRODUCT_WHOLESALE IN NUMBER,
    P_PRODUCT_RETAIL IN NUMBER,
    P_PRODUCT_IMAGE IN VARCHAR2,
    P_PRODUCT_LINK IN VARCHAR2,
    P_PRODUCT_CATEGORY IN VARCHAR2

)
AS BEGIN

    INSERT INTO INVENTORY(PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_WHOLESALE, PRODUCT_RETAIL, PRODUCT_IMAGE,
                          PRODUCT_LINK, PRODUCT_CATEGORY)
    VALUES(P_PRODUCT_NAME, P_PRODUCT_DESCRIPTION,
           P_PRODUCT_WHOLESALE, P_PRODUCT_RETAIL, P_PRODUCT_IMAGE,
           P_PRODUCT_LINK, P_PRODUCT_CATEGORY)

    RETURNING PRODUCT_ID INTO P_PRODUCT_ID;

    COMMIT ;
end;

CREATE OR REPLACE PROCEDURE p_display_inventory(
    ref_cur OUT SYS_REFCURSOR,
    p_mode IN VARCHAR2
)
AS BEGIN
        IF p_mode = 'ADMIN'
        THEN  OPEN ref_cur FOR
        SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_WHOLESALE,
        PRODUCT_RETAIL, PRODUCT_IMAGE, PRODUCT_LINK, PRODUCT_CATEGORY, STATUS
        FROM INVENTORY
        ORDER BY PRODUCT_ID DESC ;

        ELSIF p_mode = 'CUSTOMER'
        THEN  OPEN ref_cur FOR
        SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION,
        PRODUCT_RETAIL, PRODUCT_IMAGE, PRODUCT_CATEGORY
        FROM INVENTORY
        WHERE STATUS = 'Active'
        ORDER BY PRODUCT_ID DESC ;

        END IF;

end;

CREATE OR REPLACE PROCEDURE p_display_product(p_product_id IN NUMBER)
    AS
    p_product SYS_REFCURSOR;
    BEGIN
    OPEN p_product FOR
        SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_WHOLESALE, PRODUCT_RETAIL, PRODUCT_IMAGE,
               PRODUCT_LINK, PRODUCT_CATEGORY, STATUS
            FROM INVENTORY
                WHERE PRODUCT_ID = p_product_id;

    DBMS_SQL.RETURN_RESULT(p_product);

end;

CREATE OR REPLACE PROCEDURE p_verify_product(p_product_id IN NUMBER)
AS
    result_cur SYS_REFCURSOR;
BEGIN
    OPEN result_cur FOR
        SELECT PRODUCT_ID FROM INVENTORY
            WHERE PRODUCT_ID = p_product_id;

   DBMS_SQL.RETURN_RESULT(result_cur);
end;

CREATE OR REPLACE PROCEDURE p_edit_product(
    P_PRODUCT_ID IN NUMBER,
    P_PRODUCT_NAME IN VARCHAR2,
    P_PRODUCT_DESCRIPTION IN VARCHAR2,
    P_PRODUCT_WHOLESALE IN NUMBER,
    P_PRODUCT_RETAIL IN NUMBER,
    P_PRODUCT_IMAGE IN VARCHAR2,
    P_PRODUCT_LINK IN VARCHAR2,
    P_PRODUCT_CATEGORY IN VARCHAR2
)
AS
BEGIN
    UPDATE INVENTORY
    SET
    PRODUCT_NAME = p_PRODUCT_NAME,
    PRODUCT_DESCRIPTION = P_PRODUCT_DESCRIPTION,
    PRODUCT_WHOLESALE = P_PRODUCT_WHOLESALE,
    PRODUCT_RETAIL = P_PRODUCT_RETAIL,
    PRODUCT_IMAGE = P_PRODUCT_IMAGE,
    PRODUCT_LINK = P_PRODUCT_LINK,
    PRODUCT_CATEGORY = P_PRODUCT_CATEGORY

    WHERE PRODUCT_ID = P_PRODUCT_ID;

    COMMIT;

end;

CREATE OR REPLACE PROCEDURE p_delete_product(p_product_id IN NUMBER)
AS
    BEGIN
        DELETE FROM INVENTORY
               WHERE PRODUCT_ID = p_product_id;

        COMMIT ;
    end;

CREATE OR REPLACE PROCEDURE p_update_product_status(p_product_id IN NUMBER, new_status IN VARCHAR2)
AS
BEGIN
    update INVENTORY
    set STATUS = new_status
    WHERE PRODUCT_ID = p_product_id;

    COMMIT ;
END;

select * from INVENTORY;
