DECLARE
    COUNT_ROWS NUMBER;

BEGIN
    SELECT COUNT(*)
    INTO COUNT_ROWS
    FROM USER_TABLES
    WHERE TABLE_NAME = 'AUTHENTICATION';

    IF COUNT_ROWS <= 0
    THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE AUTHENTICATION
                (
                ADMIN_ID NUMBER GENERATED ALWAYS AS IDENTITY (NOCACHE) PRIMARY KEY,
                USERNAME VARCHAR2(50) NOT NULL,
                PASSWORD VARCHAR2(100) NOT NULL)';

    ELSE
        DBMS_OUTPUT.PUT_LINE('TABLE ALREADY EXISTS!');

    END IF;
END;