DECLARE
    COUNT_ROWS NUMBER;

BEGIN
    SELECT COUNT(*)
    INTO COUNT_ROWS
    FROM USER_TABLES
    WHERE TABLE_NAME = 'AUTHENTICATION';

    IF COUNT_ROWS <= 0
    THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE AUTHENTICATION
                (
                ADMIN_ID NUMBER GENERATED ALWAYS AS IDENTITY (NOCACHE) PRIMARY KEY,
                USERNAME VARCHAR2(50) NOT NULL,
                PASSWORD VARCHAR2(500) NOT NULL)';

    ELSE
        DBMS_OUTPUT.PUT_LINE('TABLE ALREADY EXISTS!');

    END IF;
END;


CREATE OR REPLACE PROCEDURE p_display_credentials(
    P_USERNAME IN VARCHAR2,
    P_HASHED_PASS OUT VARCHAR2,
    P_STATUS OUT VARCHAR2
    )
AS
    BEGIN
        SELECT PASSWORD
        INTO P_HASHED_PASS
        FROM AUTHENTICATION
        WHERE USERNAME = P_USERNAME;

        P_STATUS := 'SUCCESS';

    EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_HASHED_PASS := NULL;
        P_STATUS := 'NO USER';

    end;


CREATE OR REPLACE PROCEDURE p_change_credentials(

    P_OLD_PASSWORD IN VARCHAR2,
    P_NEW_PASSWORD IN VARCHAR2
)
AS
    BEGIN
        UPDATE AUTHENTICATION
        SET PASSWORD = P_NEW_PASSWORD
        WHERE PASSWORD = P_OLD_PASSWORD;

end;

select * from AUTHENTICATION