DECLARE
    COUNT_ROWS NUMBER;

BEGIN
    SELECT COUNT(*)
    INTO COUNT_ROWS
    FROM USER_TABLES
    WHERE TABLE_NAME = 'REVIEWS';

    IF COUNT_ROWS = 0
    THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE REVIEWS
                (
                REVIEW_ID NUMBER GENERATED ALWAYS AS IDENTITY (NOCACHE) PRIMARY KEY NOT NULL,
                NAME VARCHAR2(100) NOT NULL,
                STARS NUMBER NOT NULL,
                DESCRIPTION VARCHAR2(500),
                REVIEW_DATE DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
                REVIEW_STATUS VARCHAR2(40) DEFAULT ''VISIBLE'' NOT NULL)';
    ELSE
        DBMS_OUTPUT.PUT_LINE('TABLE REVIEWS ALREADY EXISTS!');

    END IF;
END;


CREATE OR REPLACE PROCEDURE p_add_review(
    P_NAME IN VARCHAR2,
    P_STARS IN NUMBER,
    P_DESCRIPTION IN VARCHAR2
)
AS
BEGIN
    INSERT INTO REVIEWS(NAME, STARS, DESCRIPTION)
    VALUES (P_NAME, P_STARS, P_DESCRIPTION);

    COMMIT;
end;


CREATE OR REPLACE PROCEDURE p_display_reviews(skip IN NUMBER, limit IN NUMBER, p_mode IN VARCHAR2)
AS
    ref_cur Sys_Refcursor;
BEGIN

    IF p_mode = 'ADMIN'
    THEN

        OPEN REF_CUR FOR
            SELECT REVIEW_ID, NAME, STARS, DESCRIPTION, TO_CHAR(REVIEW_DATE, 'MONTH DD, YYYY'), REVIEW_STATUS
            FROM REVIEWS
            ORDER BY REVIEW_DATE DESC, NAME
            OFFSET skip ROWS FETCH NEXT limit ROWS ONLY;

    ELSIF p_mode = 'CUSTOMER'
    THEN

        OPEN REF_CUR FOR
            SELECT NAME, STARS, DESCRIPTION, TO_CHAR(REVIEW_DATE, 'MONTH DD, YYYY')
            FROM REVIEWS
            WHERE REVIEW_STATUS = 'VISIBLE'
            ORDER BY REVIEW_DATE DESC, NAME
            OFFSET skip ROWS FETCH NEXT limit ROWS ONLY;


    END IF;

    DBMS_SQL.RETURN_RESULT(ref_cur);
END;


CREATE OR REPLACE PROCEDURE p_add_review_token(p_token IN VARCHAR2, p_order_id IN NUMBER)
AS
BEGIN
    UPDATE ORDERS
    SET REVIEW_TOKEN = p_token
    WHERE ORDER_ID = p_order_id;

    COMMIT;
END;


CREATE OR REPLACE PROCEDURE p_verify_review_status(p_review_token IN VARCHAR2)
AS
    CURRENT_STATUS SYS_REFCURSOR;

BEGIN
    OPEN CURRENT_STATUS FOR
        SELECT REVIEW_STATUS
        FROM ORDERS
        WHERE REVIEW_TOKEN = p_review_token;

    DBMS_SQL.RETURN_RESULT(CURRENT_STATUS);
END;


CREATE OR REPLACE PROCEDURE p_update_review_status(p_review_token IN VARCHAR2)
AS
BEGIN
    UPDATE ORDERS
    SET REVIEW_STATUS = 'COMPLETED'
    WHERE REVIEW_TOKEN = p_review_token;

    COMMIT;
END;


CREATE OR REPLACE PROCEDURE p_update_review_visibility(p_review_id IN NUMBER, new_status IN VARCHAR2)
AS
BEGIN
    UPDATE REVIEWS
    SET REVIEW_STATUS = new_status
    WHERE REVIEW_ID = p_review_id;

    COMMIT;
END;

CREATE OR REPLACE PROCEDURE p_delete_review(p_review_id IN NUMBER)
AS
BEGIN
    DELETE
    FROM REVIEWS
    WHERE REVIEW_ID = p_review_id;

    COMMIT;
END;


